### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by yontekh** [chaimblack/CyberSecurity#2]
NULL

**Comment by brnl** [comment]
It doesn't need to be imported. Just 'dotsourcing' is enough:
```powershell
. .\PrintNightmare-GoAway.ps1
PrintNightmare-GoAway -Logpath c:\PSLogFolder -OutResult -AddACL
```

**Comment by brnl** [comment]
@yontekh why did you remove your post? This could be interesting for others to find. :disappointed:
